
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author itopya
 */
public class PersonelArayüzü extends javax.swing.JFrame {

    public static String ID,Password;
    
    public PersonelArayüzü() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        staffInterfaceName = new javax.swing.JLabel();
        staffInterfaceSurname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amountToBeWithdrawTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        getSalaryButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        customerIDTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newLimitTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        customerIDTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        closeCreditCardButton = new javax.swing.JButton();
        createCreditCardButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        customerIDTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        currentLimitCreditCard = new javax.swing.JButton();
        newCreditCardLimitTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        increaseCreditCardLimitButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        customerIDTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        closeCustomerAccountButton = new javax.swing.JButton();
        checkAmountButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        customerIDTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        displayCustomerAccountButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Hoşgeldiniz");

        staffInterfaceName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        staffInterfaceName.setText("jLabel2");

        staffInterfaceSurname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        staffInterfaceSurname.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Maaş çek");

        amountToBeWithdrawTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountToBeWithdrawTextFieldActionPerformed(evt);
            }
        });
        amountToBeWithdrawTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountToBeWithdrawTextFieldKeyTyped(evt);
            }
        });

        jLabel3.setText("tutar");

        getSalaryButton.setText("Onayla");
        getSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSalaryButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Müşteriye Kredi Kartı Oluştur");

        customerIDTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDTextField2ActionPerformed(evt);
            }
        });
        customerIDTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerIDTextField2KeyTyped(evt);
            }
        });

        jLabel5.setText("Müşterinin ID'si");

        newLimitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLimitTextFieldActionPerformed(evt);
            }
        });
        newLimitTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newLimitTextFieldKeyTyped(evt);
            }
        });

        jLabel6.setText("Kartın Limiti");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Müşterinin Kredi Kartını Kapat");

        customerIDTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerIDTextField3KeyTyped(evt);
            }
        });

        jLabel8.setText("Müşterinin ID'si");

        closeCreditCardButton.setText("Kapat");
        closeCreditCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCreditCardButtonActionPerformed(evt);
            }
        });

        createCreditCardButton.setText("Oluştur");
        createCreditCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCreditCardButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Müşterinin Kredi Kartı Limitini Arttır");

        customerIDTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerIDTextField4KeyTyped(evt);
            }
        });

        jLabel11.setText("Müşterinin ID'si");

        currentLimitCreditCard.setText("Müşterinin Şu anki limiti");
        currentLimitCreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentLimitCreditCardActionPerformed(evt);
            }
        });

        newCreditCardLimitTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newCreditCardLimitTextFieldKeyTyped(evt);
            }
        });

        jLabel12.setText("Yeni Limiti Giriniz");

        increaseCreditCardLimitButton.setText("Onayla");
        increaseCreditCardLimitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseCreditCardLimitButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Müşteri Hesabını Kapat");

        customerIDTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerIDTextField1KeyTyped(evt);
            }
        });

        jLabel14.setText("Müşterinin ID'si");

        closeCustomerAccountButton.setText("Onayla");
        closeCustomerAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCustomerAccountButtonActionPerformed(evt);
            }
        });

        checkAmountButton.setText("İçerdeki miktarı gör");
        checkAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAmountButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Müşteri Bilgilerini Görüntüle");

        customerIDTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerIDTextField5KeyTyped(evt);
            }
        });

        jLabel16.setText("Müşterinin ID'si");

        displayCustomerAccountButton.setText("Görüntüle");
        displayCustomerAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCustomerAccountButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Giriş Ekranına Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(closeCreditCardButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(customerIDTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customerIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(closeCustomerAccountButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerIDTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkAmountButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(amountToBeWithdrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staffInterfaceName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staffInterfaceSurname)
                        .addGap(0, 200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createCreditCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getSalaryButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newCreditCardLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(increaseCreditCardLimitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(customerIDTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customerIDTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentLimitCreditCard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayCustomerAccountButton)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(staffInterfaceName)
                    .addComponent(staffInterfaceSurname))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(checkAmountButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(amountToBeWithdrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCreditCardButton)
                    .addComponent(getSalaryButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeCustomerAccountButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerIDTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeCreditCardButton)))
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerIDTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentLimitCreditCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newCreditCardLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(increaseCreditCardLimitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerIDTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayCustomerAccountButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(69, 69, 69))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void amountToBeWithdrawTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountToBeWithdrawTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountToBeWithdrawTextFieldActionPerformed

    private void customerIDTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDTextField2ActionPerformed

    private void newLimitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLimitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newLimitTextFieldActionPerformed

    private void checkAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAmountButtonActionPerformed
        BankaPersoneli p=new BankaPersoneli(Password);
        p.maaşHesabınıGör();
    }//GEN-LAST:event_checkAmountButtonActionPerformed

    private void amountToBeWithdrawTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountToBeWithdrawTextFieldKeyTyped
        PersonelArayüzü.onlyDigit(evt);
    }//GEN-LAST:event_amountToBeWithdrawTextFieldKeyTyped

    private void getSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSalaryButtonActionPerformed
       if(amountToBeWithdrawTextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(getSalaryButton, "Lütfen bir tutar girin.");
        }
       else{
           BankaPersoneli p=new BankaPersoneli(Password);
           p.maaşÇek(amountToBeWithdrawTextField.getText());
       }
    }//GEN-LAST:event_getSalaryButtonActionPerformed

    private void customerIDTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerIDTextField1KeyTyped
        PersonelArayüzü.onlyDigit(evt);
    }//GEN-LAST:event_customerIDTextField1KeyTyped

    private void closeCustomerAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCustomerAccountButtonActionPerformed
       if(customerIDTextField1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(closeCustomerAccountButton, "Lütfen bir ID girin.");
        }
       else{
           BankaPersoneli p=new BankaPersoneli();
           p.müşteriHesabınıKapat(customerIDTextField1.getText());
       }
    }//GEN-LAST:event_closeCustomerAccountButtonActionPerformed

    private void customerIDTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerIDTextField2KeyTyped
       PersonelArayüzü.onlyDigit(evt);
    }//GEN-LAST:event_customerIDTextField2KeyTyped

    private void newLimitTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newLimitTextFieldKeyTyped
       PersonelArayüzü.onlyDigit(evt);
    }//GEN-LAST:event_newLimitTextFieldKeyTyped

    private void createCreditCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCreditCardButtonActionPerformed
        if(customerIDTextField2.getText().trim().isEmpty() || newLimitTextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(createCreditCardButton, "Lütfen boş alanları doldurun");
        }
        else{
           BankaPersoneli p=new BankaPersoneli();
           p.müşteriKrediKartıOluştur(customerIDTextField2.getText(),newLimitTextField.getText() );
        }
    }//GEN-LAST:event_createCreditCardButtonActionPerformed

    private void customerIDTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerIDTextField3KeyTyped
        PersonelArayüzü.onlyDigit(evt);
    }//GEN-LAST:event_customerIDTextField3KeyTyped

    private void closeCreditCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCreditCardButtonActionPerformed
        if(customerIDTextField3.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(closeCreditCardButton, "Lütfen bir ID girin.");
        }
        else{
           BankaPersoneli p=new BankaPersoneli();
           p.müşteriKrediKartıKapat(customerIDTextField3.getText());
        }
    }//GEN-LAST:event_closeCreditCardButtonActionPerformed

    private void customerIDTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerIDTextField4KeyTyped
        PersonelArayüzü.onlyDigit(evt);
    }//GEN-LAST:event_customerIDTextField4KeyTyped

    private void currentLimitCreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentLimitCreditCardActionPerformed
        if(customerIDTextField4.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(currentLimitCreditCard, "Lütfen bir ID girin.");
        }
        else{
           BankaPersoneli p=new BankaPersoneli();
           p.müşteriLimitGör(customerIDTextField4.getText());
        }
    }//GEN-LAST:event_currentLimitCreditCardActionPerformed

    private void newCreditCardLimitTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newCreditCardLimitTextFieldKeyTyped
        PersonelArayüzü.onlyDigit(evt);
    }//GEN-LAST:event_newCreditCardLimitTextFieldKeyTyped

    private void increaseCreditCardLimitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseCreditCardLimitButtonActionPerformed
        if(customerIDTextField4.getText().trim().isEmpty() || newCreditCardLimitTextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(increaseCreditCardLimitButton, "Lütfen boş alanları doldurun");
        }
        else{
           BankaPersoneli p=new BankaPersoneli();
           p.müşteriKrediKartıLimitArttır(customerIDTextField4.getText(),newCreditCardLimitTextField.getText());
        }
    }//GEN-LAST:event_increaseCreditCardLimitButtonActionPerformed

    private void customerIDTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerIDTextField5KeyTyped
        PersonelArayüzü.onlyDigit(evt);
    }//GEN-LAST:event_customerIDTextField5KeyTyped

    private void displayCustomerAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCustomerAccountButtonActionPerformed
        if(customerIDTextField5.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(displayCustomerAccountButton, "Lütfen bir ID girin.");
        }
        else{
           BankaPersoneli p=new BankaPersoneli();
           p.müşteriBilgisiGörüntüle(customerIDTextField5.getText());
        }
    }//GEN-LAST:event_displayCustomerAccountButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main.loginAc();
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void onlyDigit(java.awt.event.KeyEvent evt){
        char TestChar=evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
            evt.consume(); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelArayüzü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelArayüzü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelArayüzü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelArayüzü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelArayüzü().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountToBeWithdrawTextField;
    private javax.swing.JButton checkAmountButton;
    private javax.swing.JButton closeCreditCardButton;
    private javax.swing.JButton closeCustomerAccountButton;
    private javax.swing.JButton createCreditCardButton;
    private javax.swing.JButton currentLimitCreditCard;
    private javax.swing.JTextField customerIDTextField1;
    private javax.swing.JTextField customerIDTextField2;
    private javax.swing.JTextField customerIDTextField3;
    private javax.swing.JTextField customerIDTextField4;
    private javax.swing.JTextField customerIDTextField5;
    private javax.swing.JButton displayCustomerAccountButton;
    private javax.swing.JButton getSalaryButton;
    private javax.swing.JButton increaseCreditCardLimitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField newCreditCardLimitTextField;
    private javax.swing.JTextField newLimitTextField;
    public static javax.swing.JLabel staffInterfaceName;
    public static javax.swing.JLabel staffInterfaceSurname;
    // End of variables declaration//GEN-END:variables
}
